// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type Title struct {
	Ru string `json:"ru"`
}

type Token struct {
	Token     string `json:"token"`
	ExpiresAt int    `json:"expiresAt"`
}

type Workhour struct {
	Day       int  `json:"day"`
	Hour      int  `json:"hour"`
	Value     bool `json:"value"`
	EveryHour bool `json:"everyHour"`
	EveryDay  bool `json:"everyDay"`
}

type Workload struct {
	SubjectID primitive.ObjectID `json:"subjectId"`
	ClassID   primitive.ObjectID `json:"classId"`
	Hours     int                `json:"hours"`
}
