// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Title struct {
	Ru string `json:"ru"`
}

type Token struct {
	Token     string `json:"token"`
	ExpiresAt int    `json:"expiresAt"`
}
