type Query {
  user: User!
  subjects: [Subject]
  table(slug: String!): Table
  classes(tableId: ID!): [Class]
  teachers(tableId: ID!): [Teacher]
}

type Mutation {
  signIn(username: String!, password: String!): Token!

  createTable(title: String!, slug: String!): Table!
  updateTable(title: String!, slug: String!, id: ID!): Table!
  deleteTable(id: ID!): Table!
  duplicateTable(id: ID!): Table!

  # createSubject(title: String!, tableId: ID!): Subject!
  # updateSubject(id: ID!, title: String!, tableId: ID!): Subject!
  # deleteSubject(id: ID!, tableId: ID!): Subject!

  createClass(
    tableId: ID!
    shift: Int!
    number: Int!
    sector: String!
    letter: String!
  ): Class!
  updateClass(
    id: ID!
    tableId: ID!
    shift: Int!
    number: Int!
    sector: String!
    letter: String!
  ): Class!
  deleteClass(id: ID!, tableId: ID!): ID

  createTeacher(tableId: ID!, name: String!, slug: String!): Teacher!
  updateTeacher(id: ID!, tableId: ID!, name: String!, slug: String!): Teacher!
  updateWorkload(
    tableId: ID!
    teacherId: ID!
    subjectId: ID!
    classId: ID!
    hours: Int!
  ): Workload!

  updateWorkhour(
    tableId: ID!
    teacherId: ID!
    day: String!
    hour: String!
    value: Boolean!
  ): Workhour!

  deleteTeacher(id: ID!, tableId: ID!): ID
}
