scalar DateTime

type Table {
  id: ID!
  title: String!
  slug: String!
  created: DateTime!
  lastModified: DateTime!
  teachers: [Teacher]
  teachersCount: Int
  classes: [Class]
  classesCount: Int
}
