type Workhour {
  day: String!
  hour: String!
  value: Boolean
}

type Workload {
  subjectId: ID!
  classId: ID!
  hours: Int
}

type Teacher {
  id: ID!
  name: String!
  slug: String!
  workload: [Workload]
  workloadAmount: Int
  workhours: [[Boolean]]
  workhoursAmount: Int
}
