type Workhour {
  day: Int!
  hour: Int!
  value: Boolean!
  everyHour: Boolean!
  everyDay: Boolean!
}

type Workload {
  subjectId: ID!
  classId: ID!
  hours: Int!
}

type Teacher {
  id: ID!
  tableId: ID!
  name: String!
  slug: String!
  workload: [Workload]
  workhours: [[Boolean]]

  subjects: Int
  classes: Int
  workhoursAmount: Int
  workloadAmount: Int
}
